### ISSUE TITLE
Logout Issue

### ISSUE THREAD

**Issue by waqas-idrees-confiz** [Azure-Samples/active-directory-xamarin-ios#4]
I am Logout using the following Code

ADAuthenticationError error;
var authenticationContext = ADAuthenticationContext.AuthenticationContextWithAuthority(IdentityAuthority, out error);
authenticationContext.TokenCacheStore.RemoveAllWithError(out error);

var cookies = NSHttpCookieStorage.SharedStorage.Cookies.ToList();
foreach (var cookie in cookies)
{
    NSHttpCookieStorage.SharedStorage.DeleteCookie(cookie);
}

After logout Login page is not showing and giving the following error

The user is currently prompted for credentials as result of another acquireToken request. Please retry the acquireToken call later.

Error is on this line
await authenticationContext.AcquireTokenWithResourceAsync(targetServerUrl, Id, redirectUri);

But if i close the application and reopen it login page successfully showing without any error

Have any idea about this

**Comment by katunch** [comment]
Same Issue here!

**Comment by jmprieur** [comment]
archiving this sample
